api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework.authtoken import views as auth_views
from rest_framework_nested.routers import NestedSimpleRouter

from api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'projects', views.ProjectViewSet)

tasks_router = NestedSimpleRouter(router, r'projects', lookup='project')
tasks_router.register(r'tasks', views.TaskViewSet)

invites_router = NestedSimpleRouter(router, r'projects', lookup='project')
invites_router.register(r'invites', views.InviteViewSet)

members_router = NestedSimpleRouter(router, r'projects', lookup='project')
members_router.register(r'members', views.ProjectMembersViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^', include(tasks_router.urls)),
    url(r'^', include(invites_router.urls)),
    url(r'^', include(members_router.urls)),
    url(r'^login/?', auth_views.obtain_auth_token, name="login"),
    url(r'^logout/?', views.LogoutView.as_view(), name="logout"),
]

base/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from base import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='base:projects-list'), name='projects-redirect'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),

    url(r'^projects/$', views.ProjectsListView.as_view(), name='projects-list'),
    url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project-detail'),
    url(r'^projects/(?P<pk>\d+)/invite/$', views.CreateInviteView.as_view(), name='project-invite'),
    url(r'^projects/(?P<pk>\d+)/update/$', views.UpdateProjectView.as_view(), name='project-update'),
    url(r'^projects/(?P<pk>\d+)/delete/$', views.DeleteProjectView.as_view(), name='project-delete'),
    url(r'^projects/new/$', views.CreateProjectView.as_view(), name='project-create'),
    url(r'^join/(?P<pk>[\w-]+)/$', views.JoinProjectView.as_view(), name='project-join'),

    url(r'^projects/(?P<project_pk>\d+)/tasks/(?P<pk>\d+)/$', views.DetailTaskView.as_view(), name='task-detail'),
    url(r'^projects/(?P<project_pk>\d+)/tasks/(?P<pk>\d+)/update/$', views.UpdateTaskView.as_view(), name='task-update'),
    url(r'^projects/(?P<project_pk>\d+)/tasks/(?P<pk>\d+)/delete/$', views.DeleteTaskView.as_view(), name='task-delete'),
    url(r'^projects/(?P<project_pk>\d+)/tasks/new/$', views.CreateTaskView.as_view(), name='task-create'),

    url(r'^projects/(?P<project_pk>\d+)/members/((?P<pk>\d+))/remove$', views.RemoveMemberFromProjectView.as_view(),
        name='member-remove'),
    url(r'^projects/(?P<project_pk>\d+)/members/((?P<pk>\d+))/change', views.ChangeRoleOnProjectView.as_view(),
        name='member-change-role'),

]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls')),
    url(r'^', include('base.urls', namespace='base'))
]

base/models.py
from __future__ import unicode_literals
import uuid

from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from mailing.shortcuts import render_send_email

from config import settings


class ProjectQuerySet(models.QuerySet):
    def by_user(self, user):
        return self.filter(Q(owner=user) | Q(managers=user) | Q(developers=user)).distinct()


class ApplicationUser(AbstractUser):
    email = models.EmailField(_('Email address'))

    def __unicode__(self):
        return "User: {0}".format(self.username)


class Project(models.Model):
    title = models.CharField(_('Title'), max_length=256)
    description = models.TextField(_('Description'), blank=True)
    owner = models.ForeignKey(ApplicationUser, verbose_name=_('Owner'), related_name='owner_projects')
    managers = models.ManyToManyField(ApplicationUser, verbose_name=_('Managers'), related_name='managers_projects', blank=True)
    developers = models.ManyToManyField(ApplicationUser, verbose_name=_('Developers'),
                                        related_name='developer_projects', blank=True)

    objects = ProjectQuerySet.as_manager()

    OWNER = 'owner'
    MANAGER = 'manager'
    DEVELOPER = 'developer'

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')

    def __unicode__(self):
        return "Project: {0}".format(self.title)

    def is_owner(self, user):
        return user == self.owner

    def is_manager(self, user):
        return self.is_owner(user) or self.managers.filter(pk=user.pk).exists()

    def is_developer(self, user):
        return self.developers.filter(pk=user.pk).exists()

    def get_absolute_url(self):
        return reverse('base:project-detail', args=(self.pk, ))

    @property
    def list_members(self):
        return self.managers.all() | self.developers.all()

    def remove_member(self, user):
        if self.is_manager(user):
            self.managers.remove(user)
        else:
            self.developers.remove(user)

    def swap_roles(self, user):
        if self.is_manager(user):
            self.managers.remove(user)
            self.developers.add(user)
        else:
            self.developers.remove(user)
            self.managers.add(user)

    def role_on_project(self, user):
        if self.is_owner(user):
            return self.OWNER
        elif self.is_manager(user):
            return self.MANAGER
        return self.DEVELOPER


class Task(models.Model):
    title = models.CharField(_('Title'), max_length=256)
    description = models.TextField(_('Description'), blank=True)
    due_date = models.DateTimeField(_('Due date'))
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    project = models.ForeignKey(Project, verbose_name=_('Project'), related_name='tasks')
    assigned_to = models.ForeignKey(ApplicationUser, verbose_name=_('Assigned to'),
                                    related_name='tasks', null=True, blank=True)

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')

    def __unicode__(self):
        return "Task: {0}".format(self.title)

    def get_absolute_url(self):
        return reverse('base:task-detail', args=(self.project_id, self.pk))


def get_uuid():
    return str(uuid.uuid4())


class Invite(models.Model):
    """Model for inviting users to the project"""

    uuid = models.UUIDField(primary_key=True, default=get_uuid)
    email = models.EmailField()
    project = models.ForeignKey(Project, null=True)

    def __unicode__(self):
        return str(self.uuid)

    def _get_invite_url(self):
        return "{}{}".format(settings.BASE_URL, reverse('base:project-join', args=(self.pk, )))

    def send(self):
        context = {'url': self._get_invite_url()}
        render_send_email([self.email, ], 'email/invite/invite', context)

base/forms/invites.py
from django import forms
from base.models import Invite


class InviteForm(forms.ModelForm):
    class Meta:
        model = Invite
        fields = ('email', )


__all__ = ['InviteForm', ]

base/forms/project.py
from django import forms

from base.models import Project


class ProjectForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        project = kwargs.get('instance', None)
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['managers'].queryset = project.list_members.exclude(pk=project.owner.pk)
        self.fields['developers'].queryset = project.list_members

    class Meta:
        model = Project
        fields = ['title', 'description', 'managers', 'developers']

base/forms/projects.py
from django import forms

from base.models import Project


class ProjectForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        project = kwargs.get('instance', None)
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['managers'].queryset = project.list_members.exclude(pk=project.owner.pk)
        self.fields['developers'].queryset = project.list_members

    class Meta:
        model = Project
        fields = ['title', 'description', 'managers', 'developers']


__all__ = ['ProjectForm', ]

base/forms/tasks.py
from django import forms

from base.models import Task


class DateInput(forms.DateInput):
    input_type = 'date'


class TaskForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        project = kwargs.pop('project')
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['assigned_to'].queryset = project.list_members

    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'assigned_to']
        widgets = {
            'due_date': DateInput()
        }


__all__ = ['TaskForm', ]

base/forms/users.py
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm, UsernameField
from base.models import ApplicationUser


class UserCreationForm(BaseUserCreationForm):

    class Meta:
        model = ApplicationUser
        fields = ("username", "email")
        field_classes = {
            'username': UsernameField
        }


__all__ = ['UserCreationForm', ]

base/views/invites.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import View
from base.forms import InviteForm
from base.mixins import PermissionsMixin
from base.permissions import IsProjectOwnerOrManagerPermission


class CreateInviteView(PermissionsMixin, View):
    http_method_names = ['post']
    permission_classes = [IsProjectOwnerOrManagerPermission, ]

    def post(self, request, *args, **kwargs):
        form = InviteForm(request.POST)
        project_id = kwargs.get('pk')
        if form.is_valid():
            invite = form.save(commit=False)
            invite.project_id = project_id
            invite.save()
            invite.send()
        messages.success(request, "Ok! Send.")
        return redirect(reverse('base:project-detail', args=(project_id, )))


__all__ = ['CreateInviteView', ]

base/views/projects.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.views.generic.base import View

from base.forms import InviteForm, ProjectForm
from base.mixins import ProjectsByUserMixin, PermissionsMixin
from base.models import Project, Invite, ApplicationUser
from base.permissions import IsProjectOwnerPermission


class ProjectsListView(LoginRequiredMixin, ProjectsByUserMixin, ListView):
    template_name = 'project/project_list.html'
    model = Project
    context_object_name = 'projects'


class ProjectDetailView(LoginRequiredMixin, ProjectsByUserMixin, DetailView):
    model = Project
    context_object_name = 'projects'
    template_name = 'project/project_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        context['invite_form'] = InviteForm()
        context['messages'] = messages.get_messages(self.request)
        return context


class CreateProjectView(CreateView):
    model = Project
    fields = ['title', 'description']
    template_name = 'project/project_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        self.object.managers.add(self.request.user)
        return super(CreateProjectView, self).form_valid(form)


class UpdateProjectView(ProjectsByUserMixin, PermissionsMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'project/project_form.html'
    permission_classes = [IsProjectOwnerPermission]


class DeleteProjectView(ProjectsByUserMixin, PermissionsMixin, DeleteView):
    model = Project
    template_name = 'project/project_confirm_delete.html'
    success_url = reverse_lazy('base:projects-list')
    permission_classes = [IsProjectOwnerPermission]


class JoinProjectView(LoginRequiredMixin, TemplateView):
    template_name = 'project/project_join.html'

    def dispatch(self, request, *args, **kwargs):
        self.pk = kwargs.get('pk')
        return super(JoinProjectView, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return get_object_or_404(Invite, pk=self.pk)

    def get_context_data(self, **kwargs):
        context = super(JoinProjectView, self).get_context_data(**kwargs)
        context['project'] = self.get_object().project

        return context

    def post(self, request, *args, **kwargs):
        project = self.get_object().project
        project.developers.add(request.user)

        return redirect(reverse('base:project-detail', args=(project.pk, )))


class RemoveMemberFromProjectView(View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        project_pk = kwargs.get('project_pk')
        member_pk = kwargs.get('pk')
        project = get_object_or_404(Project, pk=project_pk)
        member = get_object_or_404(ApplicationUser, pk=member_pk)
        project.remove_member(member)

        return redirect(reverse('base:project-detail', args=(project_pk,)))


class ChangeRoleOnProjectView(View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        project_pk = kwargs.get('project_pk')
        member_pk = kwargs.get('pk')
        project = get_object_or_404(Project, pk=project_pk)
        member = get_object_or_404(ApplicationUser, pk=member_pk)
        project.swap_roles(member)
        return redirect(reverse('base:project-detail', args=(project_pk,)))


__all__ = ['ProjectsListView', 'ProjectDetailView', 'CreateProjectView', 'DeleteProjectView',
           'UpdateProjectView', 'JoinProjectView', 'RemoveMemberFromProjectView', 'ChangeRoleOnProjectView']

base/views/tasks.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from base.forms import TaskForm
from base.mixins import ProjectTasksMixin, PermissionsMixin
from base.models import Task, Project
from base.permissions import IsTaskOwnerOrManagerPermission


class TasksListView(LoginRequiredMixin, ProjectTasksMixin, ListView):
    template_name = 'tasks.html'
    model = Task
    context_object_name = 'tasks'


class CreateTaskView(LoginRequiredMixin, PermissionsMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/task_form.html'
    permission_classes = [IsTaskOwnerOrManagerPermission, ]

    def form_valid(self, form):
        project_id = self.kwargs.get('project_pk', None)
        self.object = form.save(commit=False)
        self.object.project_id = project_id
        self.object.save()

        return super(CreateTaskView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CreateTaskView, self).get_form_kwargs()
        project = get_object_or_404(Project, pk=self.kwargs.get('project_pk', None))
        kwargs['project'] = project
        return kwargs


class DetailTaskView(LoginRequiredMixin, ProjectTasksMixin, DetailView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'tasks/task_detail.html'


class UpdateTaskView(LoginRequiredMixin, ProjectTasksMixin, PermissionsMixin, UpdateView):
    model = Task
    permission_classes = [IsTaskOwnerOrManagerPermission, ]
    template_name = 'tasks/task_form.html'
    form_class = TaskForm

    def get_form_kwargs(self):
        kwargs = super(UpdateTaskView, self).get_form_kwargs()
        project = get_object_or_404(Project, pk=self.kwargs.get('project_pk', None))
        kwargs['project'] = project
        return kwargs


class DeleteTaskView(LoginRequiredMixin, ProjectTasksMixin, PermissionsMixin, DeleteView):
    model = Task
    permission_classes = [IsTaskOwnerOrManagerPermission, ]

    def get_success_url(self):
        return reverse('base:project-detail', args=self.kwargs.get('project_pk'))


__all__ = ['TasksListView', 'CreateTaskView', 'DetailTaskView', 'UpdateTaskView', 'DeleteTaskView']

base/views/users.py
from django.views.generic import CreateView

from base.forms import UserCreationForm


class SignUpView(CreateView):
    template_name = 'registration/signup.html'
    form_class = UserCreationForm
    success_url = '/login'


__all__ = ['SignUpView', ]

base/templates/project/project_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete {{ object.title }}?</p>
            <input type="submit" value="yes" />
            <a href="{% url 'base:projects-list' %}">no</a>
        </form>
    </div>
{% endblock %}

base/templates/project/project_detail.html
{% extends 'base.html' %}
{% load project_tags %}

{% block content %}
    <div class="container">
        <h1 class="display-4">{{ object.title }}</h1>
        <blockquote class="blockquote">
            <p class="mb-0">{{ object.description }}</p>
        </blockquote>
        <h3>Tasks:</h3>
        <div>
            {% for task in object.tasks.all %}
                <a href="{% url 'base:task-detail' object.pk task.pk %}" class="list-group-item">{{ task }}</a><br/>
            {% endfor %}
            {% if user|is_manager:object %}
                <a href="{% url 'base:task-create' object.pk %}">New task</a>
            {% endif %}

        </div>
        <h3>Members:</h3>
        <div>
            <ul class="list-group">
                {% for member in object.list_members %}
                    <li class="list-group-item">
                        <h4>Username: {{ member.username }}</h4>
                        <h4>Role: {{ member|member_role:object }}</h4>
                        {% if user|is_owner:object %}
                            <div style="display: flex">
                                <form method="post" action="{% url 'base:member-remove' object.pk member.pk %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary">Remove</button>
                                </form>
                                    <form method="post" action="{% url 'base:member-change-role' object.pk member.pk  %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-primary">Change Role</button>
                                    </form>
                            </div>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% if user|is_manager:object %}
            <h3>Invite member:</h3>
            <form method="post" action="{% url 'base:project-invite' object.pk %}" class="form-inline">
                {% csrf_token %}
                <div class="form-group mx-sm-3">
                    <label for="id_email" class="sr-only">Email:</label>
                    <input id="id_email" class="form-control" maxlength="254" name="email" type="email" required="" placeholder="Email">
                </div>
                <button type="submit" class="btn btn-primary">Send</button>
            </form>

            {% for message in messages %}
                <p style="color: green">{{ message }}</p>
            {% endfor %}
        {% endif %}
        </br>
        {% if user|is_owner:object %}
            <div>
                <a href="{% url 'base:project-update' object.pk %}">Update</a>
                <a href="{% url 'base:project-delete' object.pk %}">Delete</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

base/templates/project/project_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_label">{{ form.title.label }}</label>
            <input type="text" class="form-control" id="id_label" name="title" value="{{ form.title.value }}">
        </div>
        <div class="form-group">
            <label for="id_description">{{ form.description.label }}</label>
            <textarea class="form-control" rows="5" id="id_description" name="description" >{{ form.description.value }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
    </div>
{% endblock %}

base/templates/project/project_join.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    {% if user in project.list_members %}
        <h3>Invitation accepted!</h3>
    {% else %}
        <h3>Join project {{ project.title }}</h3>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Join</button>
        </form>
    {% endif %}
    </div>

{% endblock %}

base/templates/project/project_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1 class="display-4">Projects</h1>
        <div class="list-group">
            {% for project in projects %}
                <a href="{% url 'base:project-detail' project.id %}" class="list-group-item">{{ project.title }}</a></br>
            {% endfor %}
        </div>
        <a href="{% url 'base:project-create' %}" type="button"> Add new project</a>
    </div>
{% endblock %}